import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { invoicesAPI } from '../utils/api';
import { EmptyState, StatusBadge, Pagination, PageLoader } from '../components/common/UIComponents';
import { FileText, CheckCircle, AlertTriangle, RefreshCw, Eye } from 'lucide-react';
import { format } from 'date-fns';

export default function InvoicesPage() {
  const [invoices,   setInvoices]   = useState([]);
  const [loading,    setLoading]    = useState(true);
  const [error,      setError]      = useState('');
  const [status,     setStatus]     = useState('');
  const [page,       setPage]       = useState(1);
  const [pagination, setPagination] = useState({ total: 0, pages: 1 });

  const load = async () => {
    setLoading(true); setError('');
    try {
      const r = await invoicesAPI.getAll({
        paymentStatus: status || undefined,
        page,
        limit: 15,
      });
      setInvoices(r.data.data       || []);
      setPagination(r.data.pagination || { total: 0, pages: 1 });
    } catch (e) {
      setError(e.response?.data?.message || 'Failed to load invoices');
    } finally { setLoading(false); }
  };

  useEffect(() => { load(); }, [status, page]);

  const fmt            = v  => `₹${Number(v || 0).toLocaleString('en-IN')}`;
  const totalBilled    = invoices.reduce((s, i) => s + (i.grandTotal  || 0), 0);
  const totalCollected = invoices.reduce((s, i) => s + (i.amountPaid  || 0), 0);
  const totalDue       = invoices.reduce((s, i) => s + (i.amountDue   || 0), 0);

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="page-header">
        <div>
          <h1 className="page-title">B2B Invoices</h1>
          <p className="page-subtitle">{pagination.total} invoices total</p>
        </div>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-3 gap-4">
        {[
          { label:'Total Billed',    value:fmt(totalBilled),    icon:FileText,     color:'text-blue-400',  bg:'bg-blue-500/10',  border:'border-blue-500/20'  },
          { label:'Collected',       value:fmt(totalCollected), icon:CheckCircle,  color:'text-green-400', bg:'bg-green-500/10', border:'border-green-500/20' },
          { label:'Outstanding Due', value:fmt(totalDue),       icon:AlertTriangle,color:'text-red-400',   bg:'bg-red-500/10',   border:'border-red-500/20'   },
        ].map(({ label, value, icon: Icon, color, bg, border }) => (
          <div key={label} className={`card flex items-center gap-3 border ${border} ${bg}`}>
            <div className={`w-10 h-10 rounded-xl ${bg} border ${border} flex items-center justify-center flex-shrink-0`}>
              <Icon className={`w-5 h-5 ${color}`}/>
            </div>
            <div>
              <p className={`text-lg font-bold font-display ${color}`}>{value}</p>
              <p className="text-xs text-slate-500">{label}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-2">
        {[['','All'],['pending','Pending'],['paid','Paid'],['partially_paid','Partial'],['overdue','Overdue']].map(([v, l]) => (
          <button key={v} onClick={() => { setStatus(v); setPage(1); }}
            className={`btn btn-sm ${status === v ? 'btn-primary' : 'btn-secondary'}`}>{l}</button>
        ))}
      </div>

      {loading ? <PageLoader/> : error ? (
        <div className="card border-red-500/20 bg-red-500/5 flex items-center gap-4 py-6">
          <AlertTriangle className="w-8 h-8 text-red-400 flex-shrink-0"/>
          <div className="flex-1">
            <p className="text-sm font-semibold text-red-300">Failed to load invoices</p>
            <p className="text-xs text-red-400 mt-0.5">{error}</p>
          </div>
          <button onClick={load} className="btn-secondary btn-sm">
            <RefreshCw className="w-4 h-4"/>Retry
          </button>
        </div>
      ) : invoices.length === 0 ? (
        <EmptyState
          icon={FileText}
          title="No Invoices Yet"
          description="Invoices are generated by sellers after an order is delivered. Go to an order detail page and click Generate Invoice."
        />
      ) : (
        <div className="card">
          <div className="table-wrapper">
            <table>
              <thead>
                <tr>
                  <th>Invoice #</th><th>Order #</th><th>Seller</th><th>Buyer</th>
                  <th>Total</th><th>Paid</th><th>Due</th><th>Status</th><th>Due Date</th><th></th>
                </tr>
              </thead>
              <tbody>
                {invoices.map(inv => (
                  <tr key={inv._id}>
                    <td>
                      <Link to={`/invoices/${inv._id}`}
                        className="font-mono text-xs text-brand-400 hover:text-brand-300 font-medium">
                        {inv.invoiceNumber}
                      </Link>
                    </td>
                    <td><span className="font-mono text-xs text-slate-400">{inv.order?.orderNumber || '—'}</span></td>
                    <td className="text-sm text-slate-300">{inv.seller?.company?.name || inv.seller?.name || '—'}</td>
                    <td className="text-sm text-slate-300">{inv.buyer?.company?.name  || inv.buyer?.name  || '—'}</td>
                    <td className="font-mono text-sm font-bold text-white">{fmt(inv.grandTotal)}</td>
                    <td className="font-mono text-sm text-green-400">{fmt(inv.amountPaid)}</td>
                    <td className={`font-mono text-sm font-bold ${inv.amountDue > 0 ? 'text-red-400' : 'text-slate-500'}`}>{fmt(inv.amountDue)}</td>
                    <td><StatusBadge status={inv.paymentStatus}/></td>
                    <td className="text-xs text-slate-500">
                      {inv.dueDate ? format(new Date(inv.dueDate), 'dd MMM yyyy') : '—'}
                    </td>
                    <td>
                      <Link to={`/invoices/${inv._id}`}
                        className="btn-secondary btn-sm text-xs flex items-center gap-1">
                        <Eye className="w-3.5 h-3.5"/> View
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <Pagination page={page} pages={pagination.pages} onChange={setPage}/>
        </div>
      )}
    </div>
  );
}
